name: CI - Lint, Test & Terraform Validate

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  ci-checks:
    name: Run CI Checks
    runs-on: ubuntu-latest

    env:
      PYTHON_VERSION: '3.13'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 black

      - name: Run Python linter (flake8)
        run: |
          flake8 app.py --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Format Check (black)
        run: |
          black --check app.py

      - name: Validate `requirements.txt`
        run: |
          pip check

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init -backend=false

      - name: Terraform Validate
        run: terraform validate

      - name: Show Terraform Plan (no backend)
        run: terraform plan -lock=false

