name: Deploy Flask App to EC2

on:
  push:
    branches: [ main ]
    paths:
      - 'app/**'
      - 'requirements.txt'
      - '.github/workflows/deploy-app.yml'

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    env:
      EC2_HOST: ${{ secrets.EC2_HOST }}
      SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
      SSH_USER: ubuntu

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          echo "$SSH_KEY" > private_key.pem
          chmod 600 private_key.pem

      - name: Deploy Flask App to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem $SSH_USER@$EC2_HOST << 'EOF'
            set -euxo pipefail

            cd /home/ubuntu/terraform-flask-app-clitasker-recreated

            echo "Pulling latest changes..."
            git pull origin main
            
            echo "Instalin venv if missing..."
            sudo apt update
            sudo apt install -y python3.12-venv

            echo "Setting up virtualenv..."
            python3 -m venv venv
            source venv/bin/activate

            echo "Installing requirements..."
            pip install --upgrade pip
            pip install -r app/requirements.txt

            echo "Restarting Flask app..."
            pkill flask || true
            nohup flask run --host=0.0.0.0 --port=80 > /var/log/terraform-flask-app.log 2>&1 &
          EOF


